
function ybus = ybusform(num)  % Returns ybus

linedata = linedatas(num);
fb = linedata(:,1);     % From bus number...
tb = linedata(:,2);     % To bus number...
r = linedata(:,3);      % Resistance, R...
x = linedata(:,4);      % Reactance, X...
b = linedata(:,5);      % Ground Admittance, B/2...
a = linedata(:,6);      % Tap setting value..
z = r + 1i*x;            % Z matrix(impedence)...
y = 1./z;               % element for y bus
b = 1i*b;                % admittance is imaginary

nbus = num;    % no. of buses...
nbranch = length(fb);           % no. of branches...
ybus = zeros(nbus,nbus);        % Initialise YBus...
 
 % Formation of the Off Diagonal Elements...
 for k=1:nbranch
     ybus(fb(k),tb(k)) = -y(k)/a(k);
     ybus(tb(k),fb(k)) = ybus(fb(k),tb(k));
 end
 
 % Formation of Diagonal Elements....
 for m =1:nbus
     for n =1:nbranch
         if fb(n) == m
             ybus(m,m) = ybus(m,m) + y(n) + b(n);  
         elseif tb(n) == m
             ybus(m,m) = ybus(m,m) + y(n)/(a(n)^2) + b(n); %% impedence reflection
         end
     end
 end
